### ISSUE TITLE
Thumbnails größer machen

### ISSUE THREAD

**Issue by rradczewski** [socramob/Agora#18]
Thumbnails sollten ~600x400 groß sein, damit sie überall gut aussehen.

**Comment by andreassimon** [comment]
Warum nicht quadratisch (400x400) wie bisher?

**Comment by rradczewski** [comment]
Ich würde insgesamt eher die Ratio beibehalten und dann über die max-[width|height] zur skalierung arbeiten. Die Bilder sind _immer_ 4:3, damit sieht 1:1 immer verzerrt aus :)

**Comment by andreassimon** [comment]
ok. das wird vielleicht die zeitliche anordnung später etwas aufwendiger machen, aber so weit sind wir noch nicht.

**Comment by rradczewski** [comment]
Denke auch dass wir das zurückstellen können. Für den Moment (siehe 1fa936dd7a7a80a9ff345c2154620fe34fdea790 ) haben wir ja _genug_ Differenzierung was Zeit angeht  und vor allem die Zeit unter dem Bild stehen ;)

**Comment by andreassimon** [comment]
ich würde im ersten schritt beim quadratischen verhältnis bleiben und nur die Auflösung anheben. wenn wir das seitenverhältnis ändern, birgt das für mich ein paar unwägbarkeiten, die ich nicht mehr vor der socrates aufnehmen wollen würde.

**Comment by rradczewski** [comment]
Die Höhe ist doch egal, solange max-width definiert ist sehe ich keine Probleme

**Comment by rradczewski** [comment]
Kleines Beispiel:

![image](https://cloud.githubusercontent.com/assets/418117/3810578/de3f3000-1c91-11e4-9484-c69790047944.png)

**Comment by andreassimon** [comment]
Siehe #27
