### ISSUE TITLE
Fotos für die Slideshow skalieren

### ISSUE THREAD

**Issue by andreassimon** [socramob/Agora#20]
Eine weitere Größe ~1920x1440 sollten wir zum Anzeigen des Bildes in der Slideshow verwenden um Traffic zu sparen.

Aus #18.

**Comment by leider** [comment]
Das Laden dauert viiiiiieeeel zu lange auf dem iPhone und hat wahrscheinlich auch viel zu viel Volumen

**Comment by leider** [comment]
Nochwas: Dafür, dass die Fotos so lange laden, sind sie dann aber auch viel zu klein :)

"Gut war's nicht aber dafür wenig" - auf die Frage des Kellners, wie das Essen war. _hihi_
