### ISSUE TITLE
Auf Desktop fehlt der X-close Button

### ISSUE THREAD

**Issue by leider** [socramob/Agora#21]
Wird durch den Toolbar verdeckt

**Comment by andreassimon** [comment]
Ist bei mir bisher nicht vorgekommen. Welches OS / Browser etc?

**Comment by leider** [comment]
Safari / Chrome auf Mac OS sowie Chrome auf Win7

**Comment by andreassimon** [comment]
Thx

**Comment by leider** [comment]
![tmp](https://cloud.githubusercontent.com/assets/450708/3815590/95898948-1cc6-11e4-853c-fb3aa4a589d3.png)

**Comment by leider** [comment]
Schiebt man das Genster schmal (auf mobile Niveau) gehts natürlich

**Comment by andreassimon** [comment]
Thx
