### ISSUE TITLE
Das Layout auf Desktop ist supergruselig

### ISSUE THREAD

**Issue by leider** [socramob/Agora#22]
Vorschlag: Mehrspaltenlayout a la Bootstrap

**Comment by andreassimon** [comment]
Mobile first! And only so far. ;)

**Comment by leider** [comment]
Aber anschauen will ichs doch auch auf dem Rechner!

**Comment by andreassimon** [comment]
Versteh ich. Kommt auch. Vielleicht ja beim Hackergarten?
