### ISSUE TITLE
Konsole liefert Fehler

### ISSUE THREAD

**Issue by leider** [socramob/Agora#23]
Bei http://socramob.capella.uberspace.de/activityresults/OpenSpace-2014#
-->

GET http://socramob.capella.uberspace.de/gallery/9475905d-b979-4296-af47-ac0164788a1a.JPG 404 (Not Found) OpenSpace-2014:152
GET http://socramob.capella.uberspace.de/gallery/fdd09e6d-baf1-4c44-a767-a786d22002bd.JPG?size=thumb 404 (Not Found) OpenSpace-2014:152
GET http://socramob.capella.uberspace.de/gallery/1806f88e-8ed7-4b3e-92bd-3173c9965541.JPG?size=thumb 404 (Not Found) OpenSpace-2014:153
GET http://socramob.capella.uberspace.de/gallery/36a8456a-e5fb-4f02-b5b9-31e6f815adea.png?size=thumb 404 (Not Found) OpenSpace-2014:333
GET http://socramob.capella.uberspace.de/gallery/fdd09e6d-baf1-4c44-a767-a786d22002bd.JPG?size=thumb 404 (Not Found) OpenSpace-2014:152
GET http://socramob.capella.uberspace.de/gallery/9475905d-b979-4296-af47-ac0164788a1a.JPG 404 (Not Found) OpenSpace-2014:152
GET http://socramob.capella.uberspace.de/gallery/1806f88e-8ed7-4b3e-92bd-3173c9965541.JPG?size=thumb 404 (Not Found) OpenSpace-2014:153

**Comment by andreassimon** [comment]
Memo an mich selbst: das dürften die standardbilder sein, die in der Slideshow eingestellt sind.
