### ISSUE TITLE
Bilder verzerrt und ohne Datum

### ISSUE THREAD

**Issue by leider** [socramob/Agora#24]
Schau mal da:
![tmp2](https://cloud.githubusercontent.com/assets/450708/3815800/c42596be-1cc8-11e4-8977-6d61c75a2c5a.png)

Hab ich gemacht mit mein iPhone

**Comment by andreassimon** [comment]
das liegt am motiv. ;)

**Comment by leider** [comment]
_plopp_

**Comment by andreassimon** [comment]
wir stauchen (momentan) alles auf quadratisches format.

**Comment by andreassimon** [comment]
Closed by #27.
