### ISSUE TITLE
Bilder sind viel zu klein

### ISSUE THREAD

**Issue by leider** [socramob/Agora#34]
Detaillview eines Fotos ist zu klein. Es gibt keine Möglichkeit, es in "Originalgröße" oder zumindest Fullscreen zu sehen.

**Comment by leider** [comment]
![foto](https://cloud.githubusercontent.com/assets/450708/3829080/5536526a-1d7d-11e4-9d56-0f24a5934b44.PNG)

iPhone quer

**Comment by andreassimon** [comment]
Landscape-Modus ist in der Tat noch ein großer Schmerzpunkt.

**Comment by leider** [comment]
Ist auch hochkant unerträglich. Landscape ist hier nur zur noch krasseren Verdeutlichung.

**Comment by andreassimon** [comment]
ich hatte keine bessere Idee, um genügend Platz darüber und darunter zu haben für die Navigation. Wie würdest Du es machen?
